### ISSUE TITLE
Slackはサポートされていますか？

### ISSUE THREAD

**Issue by SmallTigerFish** [ricct/jasdi#1]
マッピング実行失敗の際、メール通知の機能を確認できましたが、
Slackへ通知設定は可能ですか？

**Comment by ricctadmin** [comment]
現時点Simple Data IntegratorからSlackへ直接通知する機能がありません。

Slackの下記の機能とSDIのメール送信を合わせての利用をご検討ください。
[Slack にメールを送信する](https://slack.com/intl/ja-jp/help/articles/206819278-Slack-%E3%81%AB%E3%83%A1%E3%83%BC%E3%83%AB%E3%82%92%E9%80%81%E4%BF%A1%E3%81%99%E3%82%8B)

**Comment by SmallTigerFish** [comment]
承知しました。ありがとうございます。
