### ISSUE TITLE
ODBC 経由BigQueryに接続する際、 invalidQuery (Transaction control statements are supported only in scripts or  sessions).　エラー

### ISSUE THREAD

**Issue by SmallTigerFish** [ricct/jasdi#2]
ODBC 経由BigQueryに接続してマッピング実行する際、下記のエラーになり、実行失敗しました。
原因と解決方法を教えていただけませんか？

ERROR [HY000] [Simba][BigQuery] (100) HTTP Error 400: 
invalidQuery (Transaction control statements are supported only in scripts or 
sessions).

**Comment by ricctadmin** [comment]
ODBC コネクション設定する際、Transaction supported　という設定があります。

```
ERROR [HY000] [Simba][BigQuery] (100) HTTP Error 400:
invalidQuery (Transaction control statements are supported only in scripts or
sessions).
```
上記のエラーがでる場合、Transaction supportedをoffに設定してから試していただけませんか？

参考資料：
https://ja.sdi.ricct.com/userguide/connectionodbc/#basic
